language: go
go:
- 1.7
go_import_path: github.com/getcarina/dvm
git:
  depth: 9999999
env:
  global:
  - secure: w2xAxgBoq420qArjv6iybmzqAeiOArtc++ND/k2TiRAGbbgtjjlk1O4CEoLTsj1kHhgvN24QWNPGuYuiDgs7T7guqmPyH+hp/mgHmHAhNDrqJEfRKyBU6S5p9HXEo2fdSNEWTY3GcYfQ1WcsyVS7kFUTe8Uu5qbQKiNtfTJSwhlaHd2UI2SSdPsBugCzwlbNyhpo7mOonuK2sVxLEqfqSp68B6hiEuJK72EtCdMSi5A3sWfqqhd9+91168NzN/fo37QaP1Taiklf5rAaCmWAv+aXdUiXor7mhlXRhq/QrLV6MEkUIxowgkjlBWBe0ysP9y94puq85uGyojQVKuQ8ZNGEwRf3fiIjOsKb2E4fgZwkePY66gW8enf0PXkOqcZjFLNpQg+a0JFxd9Y2gotCAyDg2rrhlJYHjDBD/IjpPQowZ4ze9hi7AbXRQ24GWGKZ1ZYxnEmF7Xh6tcxaxLqHEPjqjIaAljGkqI9aWz7fdMIddsGhIdA8FpeU3sbC1wMqxB7STCriY6701iSHsrX9bjyekqjlvS+YxdmrHiJph+p8Xf8DCAZXyF/RDxBVWzSPedY/GaPlFsE155aCLFnwzrqj7oxOGhykCptmuSnZEoQisIDRR8Pc0FYz+6vE85cGaq3sKtW882SbmJcqYEcsXgNw3tQKKo7HAbtjEdWCsP0=
  - secure: rvculRxQ6x2T4t1aB4tdCrrPQ76M9Y1Wl6NWA8ro0fKI8+qCxL4RZ6oKL9BBYqLUsNxSkkMQUcu7nP0vVALuBA2kAfi+OFaZHqfLU+9KX/Sqi3oDv2SRCJwxEi06reEJew4g3yqqAGzNf469CLltea/9Ssktmga6uF55/Xqrm3EGc/e/sYC4JMzi1yOnyTbZuz3x6S7NtfplVp7aTlWl2X6OAHiJiQnmo27RjTRIsUy71RKykcAn8awsx03tZXusnSRDGm4bj0JhNw7C7fV7Zu3ovvdQeapNqFotsVthB0HdfnnuT7mtC6gtpNO3HdlXOd0uiqGCSXO4EYTlOaNCyDiz0xcd+JQlulMAPX64RfCguoXUjyVlWdjn0mjLd+vcgrijdnp/wkfqrqDjz3Wclc3/nI+/wvWRezuLbq97wmQo+sRD5rIRNQ3drR0uXbnaXWGg2ULjPbk2wMNSISeIAnwf0brbRbw1k5TCawE5tF4WaNjxDSIjlkDzU7/zKO8eZjK1Ccu2dnjXHnXP/3iriHh0SB9SGjJxE3ZMSTpOtkL9mbJP153sv9wt/HF54KtUXs12t02v63bc7HjwWzLqk4ZDcTks9N6UjBsVq4kxdntd30aHzYNdeb1r8Aslyw0pDmI7dWXgAwZaPZC2VKBn3bpV8de7VdgShkHaDrH8r1k=
  - secure: JRAezKJaRS3xK936tty0A5xEFvhKLKxSBHsb5JhP7WOCZ4sVQ7fegRSgJv9QyR96rza3fRvjAI7X77lIRzvEmpmi6UnCGrAEsCSG0I791RQv40Nkpgmlmu1lXzS8JvpsiXVHCa/CuewYT2ucLeBBb8TOj4BCP5fA8SaTvWrOc+yacQ2MoqDpF/RAqjxclzDWoSBtqKPfkYQY1Uu9G2WN2HSngRB6lq6JqRG0jgbVZhbxfYnhOqLCX+J61mNSjUCg9ukwrP01/1WY29VrtGM9QE5HWf/xgAChQt/Upas6/5dQ8PCsbaOAR1c+EUg5JDHXHXqqGwwoocmNaasKv6dL5YScETqst1O8gIsKd2MFzaV0g1m50a3NIk09eXJh0EZW/vEfJqqTI8QRTUWLCiV+5QooX76mUx0VUSM0VKdWL13IFCFOzjw+vSve65FFpZZ+LBBeEheXYRL8dik2Np7k/wd2GTatArrTynNfhmtxfoWpvTW3qZt5bTxj2v6F0AqbVq8m95ho+Bx6t4FviIZxq0eCM7e2oxsBepsdrZ/3/mOwFI3t6fNo/Q42QY4yN72Z9pzdpYmFkM8wuUXq5Lv8eV3umql5qA1U9gK4gszyYUP7ZMROKc9nRGZ1SSSDFerj+WP586NG6DzxflqKAXpVzLdQ1wqwejIMqeligB1IEJQ=
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    repo: getcarina/dvm
    tags: true
