language: go
go:
- 1.7
go_import_path: github.com/howtowhale/dvm
git:
  depth: 9999999
install:
- make get-deps
script:
- make test
- make cross-build
before_deploy:
- openssl aes-256-cbc -K $encrypted_79d16d43cbac_key -iv $encrypted_79d16d43cbac_iv -in script/travis.deploy.pem.enc -out script/travis.deploy.pem -d
deploy:
- provider: script
  script: make deploy
  skip_cleanup: true
  on:
    repo: howtowhale/dvm
    tags: true

